### ISSUE TITLE
我用rnpm link后运行报错

### ISSUE THREAD

**Issue by WaterEye0o** [1123746696/react-native-umeng-analytics#1]
<img width="419" alt="b6c0495b-2462-4974-812d-89827a3e7c04" src="https://cloud.githubusercontent.com/assets/15081830/18083113/370f5e12-6ed4-11e6-96ca-d403f556a780.png">

**Comment by 1123746696** [comment]
请在你的工程目录结构中，添加友盟统计框架，在选项TARGETS--> Build Phases-->Link Binary With Libraries-->Add Other，选择文件node_modules/react-native-umeng-analytics/ios/umsdk_IOS_analyics_idfa_v4.0.4/UMMobClick.framework

**Comment by WaterEye0o** [comment]
@1123746696 添加完后报这个错误

**Comment by WaterEye0o** [comment]
@1123746696 添加完后报这个错误

ld: framework not found UMMobClick
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by 1123746696** [comment]
添加友盟框架引用,在TARGETS-->Build Settings-->Framework Search Paths, 添加:$(SRCROOT)/../node_modules/react-native-umeng-analytics/ios/umsdk_IOS_analyics_idfa_v4.0.4

**Comment by WaterEye0o** [comment]
@1123746696  ok跑起来了 谢谢啦
