### ISSUE TITLE
集成后启动报错

### ISSUE THREAD

**Issue by wooilung** [1123746696/react-native-umeng-analytics#2]
ios版本集成编译成功后，启动报错。麻烦帮忙看一下！谢谢

![image](https://cloud.githubusercontent.com/assets/2063253/19226579/75cde6fc-8edf-11e6-9011-d9e26bd6019e.png)

**Comment by 1123746696** [comment]
用下边的方法 
 UMConfigInstance.appKey = key;
  UMConfigInstance.channelId = channelId;
  [MobClick startWithConfigure:UMConfigInstance];
